# Change these first
owner: sankar-shunmuga # Your GitHub organization or username, where this repository lives
repo: NWP-Monitor-Tool # The name of this repository

sites:
  - name: LKS
    url: https://library.hee.nhs.uk
  - name: Digital Transformation
    url: https://digital-transformation.hee.nhs.uk
  - name: Dental
    url: https://dental.hee.nhs.uk
  - name: Medical
    url: https://medical.hee.nhs.uk
  - name: GP Recruitment
    url: https://gprecruitment.hee.nhs.uk
  - name: GP Recruitment Prod
    url: https://gprecruitment-prod.hee.nhs.uk
  - name: KFH Library Services 
    url: https://kfh.libraryservices.nhs.uk
  - name: Staging
    url: https://staging.hee.nhs.uk
    expectedStatusCodes:
      - 200      
      - 401    
  - name: Webstie Testing
    url: https://website-testing.hee.nhs.uk
    expectedStatusCodes:
      - 200      
      - 401
  - name: Feedback
    url: https://feedback.hee.nhs.uk
    expectedStatusCodes:
      - 200      
      - 401
  - name: Workforce Education
    url: https://workforce-education.hee.nhs.uk
    expectedStatusCodes:
      - 200      
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /NWP-Monitor-Tool
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
